---
title:               Factory Labs Code Blog
tagline:             Kronkity Fliz.
login:               <%= ENV["obtvse_login"] ? ENV["obtvse_login"] : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
google_analytics_id: YOUR_GA_ID
